// skillIcons.ts
import {
  Code2, Terminal, Braces,
  Atom, CircuitBoard, SquareStack,
  FileCode, LayoutTemplate, Code,
  Database, GitBranch, GitCommit,
  FunctionSquare, BrainCircuit,
  Table, Presentation, FileText,
  PenTool, Brush, Palette,
  Film, Search, BarChart2,
  Share2, Pen, StickyNote,
  DollarSign, TrendingUp,
  Camera, Music, Mic,
  Cpu, Settings, Cloud, Shield, Lock
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

export const skillIconMap: Record<string, LucideIcon> = {
  'Python': Code2,
  'Java': Terminal,
  'C++': Braces,
  'React': Atom,
  'Node.js': CircuitBoard,
  'Next.js': SquareStack,
  'HTML': FileCode,
  'CSS': LayoutTemplate,
  'JavaScript': Code,
  'SQL': Database,
  'MongoDB': Database,
  'Git & GitHub': GitBranch,
  'Data Structures & Algorithms': FunctionSquare,
  'Machine Learning': BrainCircuit,
  'Excel': Table,
  'PowerPoint': Presentation,
  'Resume Building': FileText,
  'Graphic Design': PenTool,
  'Canva': Palette,
  'Adobe Photoshop': Brush,
  'Video Editing': Film,
  'SEO': Search,
  'Social Media Management': Share2,
  'Blogging': StickyNote,
  'Financial Literacy': DollarSign,
  'Stock Market Basics': TrendingUp,
  'Photography': Camera,
  'Guitar': Music,
  'Singing': Mic,
  'Robotics': Cpu,
  'Arduino': Settings,
  'Cloud Computing Basics': Cloud,
  'Cybersecurity Basics': Shield,
}
